#!/bin/bash
#
# LSF batch script to run an MPI application
#
#BSUB -P STDD0002            # project code
#BSUB -W 02:00               # wall-clock time (hrs:mins)
#BSUB -n 64                  # number of tasks in job
#BSUB -R "span[ptile=16]"    # run 16 MPI tasks per node
#BSUB -J checkresults        # job name
#BSUB -o checkresults.%J.out # output file name in which %J is replaced by the job ID
#BSUB -q small               # queue

#run the executable
mpirun.lsf ./checkresults.py
